import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from './assets/vite.svg'
import heroImg from './assets/hero.png'
import './App.css'

import React, { useEffect, useState } from 'react';

function App() {
  const [logMessage, setLogMessage] = useState('Checking URL for tracking parameters...');
  const siteUrl = "product.html"; // Your target outbound link

  useEffect(() => {
    // 1. Grab the global Everflow object we loaded in index.html
    const { EF } = window;

    if (!EF) {
      setLogMessage('❌ Everflow SDK not detected. Make sure the script is in index.html!');
      return;
    }

    const oid = EF.urlParameter('oid');
    const affid = EF.urlParameter('affid');
    const tid = EF.urlParameter('_ef_transaction_id');
    const advertiserId = "12345"; // Test Advertiser ID

    // 2. Helper function to find links and update them
    const updateLinks = (trackingId) => {
      const elems = document.getElementsByTagName('a');
      for (let i = 0; i < elems.length; i++) {
        if (elems[i].href.includes(siteUrl)) {
          const url = new URL(elems[i].href);
          url.searchParams.set('_ef_transaction_id', trackingId);
          elems[i].href = url.href;
        }
      }
    };

    // 3. Last-Touch/Organic Logic Gate
    const existingTid = EF.getAdvertiserTransactionId(advertiserId);

    if (existingTid && !affid) {
      setLogMessage(`♻️ Organic returning user. Reusing TID: ${existingTid}`);
      updateLinks(existingTid);
    } else if (oid && affid) {
      setLogMessage(`⏳ New partner link detected (affid: ${affid}). Firing click...`);
      
      EF.click({
        offer_id: oid,
        affiliate_id: affid,
        source_id: EF.urlParameter('source_id'),
        sub1: EF.urlParameter('sub1'),
      }).then((transactionId) => {
        if (transactionId) {
          setLogMessage(`✅ Click Tracked! Generated TID: ${transactionId}`);
          updateLinks(transactionId);
        } else {
          setLogMessage('⚠️ Click fired, but no TID generated by Everflow.');
        }
      });
    } else {
      setLogMessage('❌ No tracking parameters in URL. Try appending: ?oid=123&affid=456');
    }
  }, []); // Empty array means this runs ONCE when the page loads

  // --- YOUR HTML / JSX GOES HERE ---
  return (
    <div style={{ fontFamily: 'sans-serif', maxWidth: '700px', margin: '0 auto', padding: '20px' }}>
      <header style={{ borderBottom: '2px solid #eee', paddingBottom: '10px', marginBottom: '30px' }}>
        <div style={{ fontWeight: 'bold', fontSize: '24px', color: '#ff4757' }}>⚡ TechVibe Magazine</div>
        <div style={{ color: '#777', fontSize: '14px' }}>Published July 2026 • React Edition</div>
      </header>

      <main>
        <h1>The Best React Gadget Listicles of 2026</h1>
        <p>This page is running dynamically inside a React component wrapper!</p>

        {/* Listicle Item */}
        <div style={{ background: '#f9f9f9', border: '1px solid #ddd', padding: '20px', borderRadius: '8px', marginBottom: '25px' }}>
          <h2>1. AeroPods Pro Max (2026 Edition)</h2>
          <p>The active noise cancellation on these new headphones is scary good.</p>
          <a href="product.html" style={{ display: 'inline-block', background: '#2ed573', color: 'white', padding: '10px 20px', textDecoration: 'none', borderRadius: '5px', fontWeight: 'bold' }}>
            Check Price on Amazon &rarr;
          </a>
        </div>
      </main>

      {/* Live Logging Panel */}
      <div style={{ background: '#2f3542', color: '#a4b0be', padding: '15px', borderRadius: '5px', fontFamily: 'monospace', marginTop: '40px' }}>
        <div style={{ color: '#ff6b81', fontWeight: 'bold', marginBottom: '5px' }}>[EVERFLOW REACT LIVE LOGS]</div>
        <div>{logMessage}</div>
      </div>
    </div>
  );
}

export default App;